# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# Hexo Beautify 
beautify:
  types:
    - html
    - css
    - js
  exclude:
    - '*.min.css'
    - '*.min.js'
  html:
    'indent_inner_html': false
    'indent_size': 2
    'indent_with_tabs': false
    # More Options (https://github.com/beautify-web/js-beautify/blob/master/README.md) 
  css:
    'indent_size': 2
    'newline_between_rules': true
    'indent_with_tabs': false
    # More Options (https://github.com/beautify-web/js-beautify/blob/master/README.md) 
  js:
    'indent_size': 2
    'indent_with_tabs': false
    # More Options (https://github.com/beautify-web/js-beautify/blob/master/README.md)

postcss:
	plugins:
		postcss-import: {}
		postcss-media-minmax: {}
		postcss-custom-media: {}
		postcss-aspect-ratio: {}
		postcss-layout: {}
		autoprefixer: {}